# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ViewControllerLifeCycleProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViewControllerLifeCycleProject
	
    pod 'SnapKit', '~> 5.0.0'



  target 'ViewControllerLifeCycleProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ViewControllerLifeCycleProjectUITests' do
    # Pods for testing
  end

end
